# Generated by Django 5.1.3 on 2024-12-03 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poke_type', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
